import { contextBridge, ipcRenderer } from 'electron';

const invoke = (name: string, input?: unknown) => ipcRenderer.invoke(`reupmatic:${name}`, input);
function subscribe<T>(channel: string, callback: (data: T) => void) {
  const listener = (_event: unknown, data: T) => callback(data);
  ipcRenderer.on(`reupmatic:${channel}`, listener);
  return () => ipcRenderer.removeListener(`reupmatic:${channel}`, listener);
}

// Only allowlisted verbs cross this boundary; neither helper is exposed.
contextBridge.exposeInMainWorld('reupmatic', {
  catalogSnapshot: () => invoke('catalog-snapshot'),
  onCatalogChanged: (callback: () => void) => subscribe('catalog-changed', callback),
  catalogSaveLabel: (input: unknown) => invoke('catalog-save-label', input),
  catalogContentLabels: (input: unknown) => invoke('catalog-content-labels', input),
  channelSave: (input: unknown) => invoke('channel-save', input),
  affiliateSave: (input: unknown) => invoke('affiliate-save', input),
  postList: (input: unknown) => invoke('post-list', input),
  postExportChoices: () => invoke('post-export-choices'),
  postCreate: (input: unknown) => invoke('post-create', input),
  postEdit: (input: unknown) => invoke('post-edit', input),
  postReveal: (id: string) => invoke('post-reveal', { id }),
  profileSave: (input: unknown) => invoke('profile-save', input),
  profileRead: () => invoke('profile-read'),
  profileExport: (id: string) => invoke('profile-export', { id }),
  workflowPickOutput: () => invoke('workflow-pick-output'),
  workflowSave: (input: unknown) => invoke('workflow-save', input),
  workflowRun: (input: unknown) => invoke('workflow-run', input),
  recoveryList: () => invoke('recovery-list'),
  recoverySave: (input: unknown) => invoke('recovery-save', input),
  recoveryOpen: (input: unknown) => invoke('recovery-open', input),
  recoveryDiscard: (input: unknown) => invoke('recovery-discard', input),
  onRecoveryFlush: (callback: (input: { request_id: string }) => void) => subscribe('recovery-flush', callback),
  recoveryFlushResult: (request_id: string, saved: boolean) => invoke('recovery-flush-result', { request_id, saved }),
  hello: () => invoke('hello'),
  open: () => invoke('open'),
  compositionStart: (asset_id: string) => invoke('composition-start', { asset_id }),
  compositionPick: () => invoke('composition-pick'),
  compositionPreview: (input: unknown) => invoke('composition-preview', input),
  audioPick: () => invoke('audio-pick'),
  audioPreview: (input: unknown) => invoke('audio-preview', input),
  importSubtitles: () => invoke('import-subtitles'),
  ass: (input: unknown) => invoke('ass', input),
  peaks: (input: unknown) => invoke('peaks', input),
  render: (input: unknown) => invoke('render', input),
  cancel: (request_id: string) => invoke('cancel', { request_id }),
  saveSubtitles: (input: unknown) => invoke('save-subtitles', input),
  saveVideo: (artifact_id: string) => invoke('save-video', { artifact_id }),
  openProject: () => invoke('open-project'),
  saveProject: (input: unknown) => invoke('save-project', input),
  onJob: (callback: (data: unknown) => void) => subscribe('job', callback),
  synthesisStatus: () => invoke('synthesis-status'),
  synthesisStart: (input: unknown) => invoke('synthesis-start', input),
  synthesisCancel: (request_id: string) => invoke('synthesis-cancel', { request_id }),
  synthesisConfigure: () => invoke('synthesis-configure'),
  synthesisCancelSetup: () => invoke('synthesis-cancel-setup'),
  synthesisPreview: (artifact_id: string) => invoke('synthesis-preview', { artifact_id }),
  synthesisChooseExport: (artifact_id: string, kind: string) => invoke('synthesis-choose-export', { artifact_id, kind }),
  synthesisSave: (choice_id: string, artifact_id: string) => invoke('synthesis-save', { choice_id, artifact_id }),
  synthesisCancelExport: () => invoke('synthesis-cancel-export'),
  onSynthesisJob: (callback: (data: unknown) => void) => subscribe('synthesis-job', callback),
  onSynthesisModelsChanged: (callback: () => void) => subscribe('synthesis-models-changed', callback),
  translationStatus: () => invoke('translation-status'),
  translationStart: (input: unknown) => invoke('translation-start', input),
  translationCancel: (request_id: string) => invoke('translation-cancel', { request_id }),
  translationConfigure: () => invoke('translation-configure'),
  translationCancelSetup: () => invoke('translation-cancel-setup'),
  onTranslationJob: (callback: (data: unknown) => void) => subscribe('translation-job', callback),
  onTranslationModelsChanged: (callback: () => void) => subscribe('translation-models-changed', callback),
  speechStatus: () => invoke('speech-status'),
  speechStart: (input: unknown) => invoke('speech-start', input),
  speechCancel: (request_id: string) => invoke('speech-cancel', { request_id }),
  speechConfigure: () => invoke('speech-configure'),
  speechCancelSetup: () => invoke('speech-cancel-setup'),
  onSpeechJob: (callback: (data: unknown) => void) => subscribe('speech-job', callback),
  onSpeechModelsChanged: (callback: () => void) => subscribe('speech-models-changed', callback),
  visionStatus: () => invoke('vision-status'),
  visionStart: (input: unknown) => invoke('vision-start', input),
  visionCancel: (request_id: string) => invoke('vision-cancel', { request_id }),
  onVisionJob: (callback: (data: unknown) => void) => subscribe('vision-job', callback),
  batchSnapshot: () => invoke('batch-snapshot'),
  batchPickVideos: () => invoke('batch-pick-videos'),
  batchFromLibrary: (item_ids: string[]) => invoke('batch-from-library', { item_ids }),
  batchPickSubtitle: () => invoke('batch-pick-subtitle'),
  batchPickDirectory: () => invoke('batch-pick-directory'),
  batchEnqueue: (input: unknown) => invoke('batch-enqueue', input),
  batchPause: () => invoke('batch-pause'),
  batchResume: () => invoke('batch-resume'),
  batchCancel: (job_id: string) => invoke('batch-cancel', { job_id }),
  batchRetry: (job_id: string) => invoke('batch-retry', { job_id }),
  batchReveal: (job_id: string) => invoke('batch-reveal', { job_id }),
  onBatch: (callback: (data: unknown) => void) => subscribe('batch', callback),
  folderSnapshot: () => invoke('folder-snapshot'),
  folderPickSource: () => invoke('folder-pick-source'),
  folderPickOutput: () => invoke('folder-pick-output'),
  folderCreate: (input: unknown) => invoke('folder-create', input),
  folderStart: (rule_id: string) => invoke('folder-start', { rule_id }),
  folderPause: (rule_id: string) => invoke('folder-pause', { rule_id }),
  onFolders: (callback: (data: unknown) => void) => subscribe('folders', callback),
  libraryAssets: (input: unknown) => invoke('library-assets', input),
  libraryAssetAttach: (input: unknown) => invoke('library-asset-attach', input),
  libraryAssetCheck: (input: unknown) => invoke('library-asset-check', input),
  libraryAssetPreview: (input: unknown) => invoke('library-asset-preview', input),
  libraryList: (input: unknown) => invoke('library-list', input),
  libraryImport: (input: unknown) => invoke('library-import', input),
  libraryCancelImport: () => invoke('library-cancel-import'),
  libraryOpen: (item_id: string) => invoke('library-open', { item_id }),
  libraryOpenProject: (item_id: string, link_id: string) => invoke('library-open-project', { item_id, link_id }),
  libraryRelink: (item_id: string) => invoke('library-relink', { item_id }),
  libraryDependencies: (item_id: string) => invoke('library-dependencies', { item_id }),
  libraryForget: (item_id: string) => invoke('library-forget', { item_id }),
  libraryReveal: (item_id: string, link_id?: string) => invoke('library-reveal', {
    item_id, ...(link_id ? { link_id } : {}),
  }),
  onLibraryChanged: (callback: () => void) => subscribe('library-changed', callback),
  onLibraryImport: (callback: (data: unknown) => void) => subscribe('library-import', callback),
  settingsSnapshot: () => invoke('settings-snapshot'),
  settingsPickOutput: () => invoke('settings-pick-output'),
  settingsClearOutput: () => invoke('settings-clear-output'),
  settingsPickModels: () => invoke('settings-pick-models'),
  settingsCancelModels: () => invoke('settings-cancel-models'),
  onModelsChanged: (callback: () => void) => subscribe('models-changed', callback),
  dirty: (dirty: boolean, language: string) => invoke('dirty', { dirty, language }),
});
