import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const ui = path.join(root, 'app/ui');

function cssFiles(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const filename = path.join(directory, entry.name);
    if (entry.isDirectory()) return cssFiles(filename);
    return filename.endsWith('.css') ? [filename] : [];
  });
}

// Styling an Astryx internal (`.astryx-*`) is prohibited unless it is a genuine design-system gap.
// Each entry records the reason its override is sanctioned rather than hand-waving the selector.
const ALLOWED_ASTRYX_SELECTORS = {
  '.astryx-collapsible-trigger': 'No per-instance width/size control on a `Collapsible` trigger',
  '.astryx-app-shell-header': '`xstyle` cannot compile in this repo today',
  '.astryx-app-shell-sidenav': '`xstyle` cannot compile in this repo today',
};

// The generated theme stylesheet emits whatever `.astryx-*` selectors `defineTheme` compiles
// to — that is the sanctioned override mechanism, not a hand-written override, so it is exempt
// from this scanner. It is a build artifact (gitignored), not app-authored CSS.
function isGenerated(source) {
  return source.startsWith('/*\n * @generated by `astryx theme build`');
}

test('app/ui CSS never styles an Astryx internal outside the recorded gap list', () => {
  const offenders = [];
  for (const file of cssFiles(ui)) {
    const source = readFileSync(file, 'utf8');
    if (isGenerated(source)) continue;
    for (const match of source.matchAll(/\.astryx-[a-z0-9-]+/g)) {
      if (!Object.hasOwn(ALLOWED_ASTRYX_SELECTORS, match[0])) {
        offenders.push(`${path.relative(root, file)}: ${match[0]}`);
      }
    }
  }
  assert.deepEqual(
    offenders,
    [],
    'Unrecorded .astryx-* override(s) — fix the styling, or add an allow-list entry here with its ' +
      'reason:\n' +
      offenders.join('\n'),
  );
});
