// Electron's sandboxed preload (webPreferences.sandbox: true) runs in a restricted loader that
// cannot `require()` other project files — only the preload script itself. `preload.cts` is
// therefore only the *source of truth* for the mechanism; this script inlines the canonical
// registries' renderer-facing data (name, rendererMethod, toRequest) into a fully self-contained
// `dist-node/electron/preload.cjs`, replacing the naive compiled output. Runs after
// `tsc -p tsconfig.node.json` so `dist-node/core/host-bridge/*.js` already exists.
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const distNode = path.join(root, 'dist-node');

const { operations } = await import(path.join(distNode, 'core/host-bridge/operations.js'));
const { events } = await import(path.join(distNode, 'core/host-bridge/events.js'));

function operationLine(name, entry) {
  const call = entry.toRequest ? `(${entry.toRequest.toString()})(...args)` : 'args[0]';
  return `  exposed[${JSON.stringify(entry.rendererMethod)}] = (...args) => invoke(${JSON.stringify(name)}, ${call});`;
}

function eventLine(name, entry) {
  return `  exposed[${JSON.stringify(entry.rendererMethod)}] = (callback) => subscribe(${JSON.stringify(name)}, callback);`;
}

const operationLines = Object.entries(operations)
  .map(([name, entry]) => operationLine(name, entry))
  .join('\n');
const eventLines = Object.entries(events)
  .map(([name, entry]) => eventLine(name, entry))
  .join('\n');

const generated = `"use strict";
// GENERATED by scripts/generate-preload.mjs from app/core/host-bridge/{operations,events}.ts.
// Do not edit directly; edit the registries (or app/electron/preload.cts for the mechanism) and
// rebuild. Self-contained: Electron's sandboxed preload loader cannot require other project files.
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const invoke = (name, input) => electron_1.ipcRenderer.invoke(\`reupmatic:\${name}\`, input);
function subscribe(channel, callback) {
  const listener = (_event, data) => callback(data);
  electron_1.ipcRenderer.on(\`reupmatic:\${channel}\`, listener);
  return () => electron_1.ipcRenderer.removeListener(\`reupmatic:\${channel}\`, listener);
}
const exposed = {};
${operationLines}
${eventLines}
// Mirrors preload.cts's own getPathForFile exposure (webUtils.getPathForFile is not a wire
// operation, so it isn't in the operations registry this generator otherwise reads from).
exposed.getPathForFile = (file) => electron_1.webUtils.getPathForFile(file);
electron_1.contextBridge.exposeInMainWorld("reupmatic", exposed);
`;

await writeFile(path.join(distNode, 'electron', 'preload.cjs'), generated);
console.log('Generated dist-node/electron/preload.cjs from the host-bridge registries.');
