import argparse
import copy
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ROOT / "contracts"
METADATA = {"$schema", "$id", "$comment", "title", "description"}

# Hand-authored: not derivable from the request schema, which knows only param shape.
INSTANT_METHODS = frozenset(
    {"cancel", "hello", "models.status", "speech.status", "synthesis.status", "translation.status"}
)

# Hand-authored: seam-generic phases emitted by the generic accept/dispatch loop.
PROGRESS_PHASES = {"PROGRESS_QUEUED": "queued", "PROGRESS_RUNNING": "running"}


def biome_format(text, name):
    biome = ROOT / "node_modules" / ".bin" / ("biome.cmd" if sys.platform == "win32" else "biome")
    result = subprocess.run(
        [str(biome), "format", f"--stdin-file-path={name}"],
        input=text,
        capture_output=True,
        text=True,
        encoding="utf-8",
        cwd=ROOT,
    )
    if result.returncode != 0:
        raise SystemExit(f"biome format failed for {name}: {result.stderr}")
    return result.stdout


def ruff_format(text):
    # Ruff is a dev tool, not a worker runtime; format only when it is installed.
    if importlib.util.find_spec("ruff") is None:
        return text
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "-"],
        input=text,
        capture_output=True,
        text=True,
        encoding="utf-8",
        cwd=ROOT,
    )
    if result.returncode != 0:
        raise SystemExit(f"ruff format failed: {result.stderr}")
    return result.stdout


def operations_module(worker_request_schema):
    branches = worker_request_schema["allOf"][1]["oneOf"]
    all_methods = frozenset(branch["properties"]["method"]["const"] for branch in branches)
    unknown_instant = INSTANT_METHODS - all_methods
    if unknown_instant:
        raise SystemExit(
            f"INSTANT_METHODS names not in worker-request.schema.json: {unknown_instant}"
        )
    queued_methods = all_methods - INSTANT_METHODS

    def literal_set(methods):
        items = ", ".join(json.dumps(name) for name in sorted(methods))
        return f"frozenset({{{items}}})"

    return (
        '"""Generated by scripts/sync-contracts.py from contracts/worker-request.schema.json.\n\n'
        "Do not edit by hand; edit the canonical per-domain schemas, then regenerate.\n"
        '"""\n\n'
        f"INSTANT_METHODS: frozenset[str] = {literal_set(INSTANT_METHODS)}\n\n"
        f"QUEUED_METHODS: frozenset[str] = {literal_set(queued_methods)}\n\n"
        "METHODS: frozenset[str] = INSTANT_METHODS | QUEUED_METHODS\n\n"
        + "\n\n".join(
            f"{name}: str = {json.dumps(value)}" for name, value in PROGRESS_PHASES.items()
        )
        + "\n\n"
        f"PROGRESS_PHASES: frozenset[str] = frozenset({{{', '.join(PROGRESS_PHASES.keys())}}})\n"
    )


def read(name):
    return json.loads((CONTRACTS / name).read_text(encoding="utf-8"))


def source_name(name):
    # Outputs are overwritten each run, so they cannot be their own base template.
    return name.replace(".schema.json", ".source.schema.json")


def read_source(name):
    return read(source_name(name))


def shape(value):
    return {key: copy.deepcopy(child) for key, child in value.items() if key not in METADATA}


def object_schema(properties, required):
    return {
        "type": "object",
        "properties": properties,
        "required": required,
        "additionalProperties": False,
    }


def compose():
    style = shape(read("subtitles/style.schema.json"))
    editing = shape(read("editing/recipe.schema.json"))
    soundtrack = shape(read("editing/soundtrack.schema.json"))
    composition = shape(read("editing/composition.schema.json"))
    translation = read("speech/translation.schema.json")["$defs"]
    synthesis = read("speech/synthesis.schema.json")["$defs"]
    layer_document = read_source("subtitles/text-layers.schema.json")
    for name in ["transcript", "translated", "spoken", "displayed"]:
        origins = layer_document["properties"][name]["properties"]["origin"]["oneOf"]
        origins[:] = [
            origin
            for origin in origins
            if origin["properties"]["kind"].get("const") != "translation"
        ]
        origins.append(copy.deepcopy(translation["origin"]))
    layers = shape(layer_document)
    speech = read("speech/recognition.schema.json")["$defs"]
    cues = read_source("cues.schema.json")
    cues["items"]["properties"]["style"] = style
    processing = read_source("processing.schema.json")
    processing["properties"]["editing"] = editing
    processing["properties"]["subtitle_style"] = style
    processing["anyOf"] = [
        {"required": [key]} for key in ["ocr", "inpaint", "editing", "subtitle_style"]
    ]

    def embedded(value):
        if isinstance(value, list):
            return [embedded(child) for child in value]
        if not isinstance(value, dict):
            return value
        properties = value.get("properties", {})
        if {"ocr", "inpaint", "subtitle_style"} <= properties.keys():
            return shape(processing)
        if (
            value.get("type") == "array"
            and {"id", "start_ms", "end_ms", "text"}
            <= value.get("items", {}).get("properties", {}).keys()
        ):
            return shape(cues)
        return {key: embedded(child) for key, child in value.items()}

    outputs = {
        "subtitles/text-layers.schema.json": layer_document,
        "cues.schema.json": cues,
        "processing.schema.json": processing,
    }
    for name in [
        "project.schema.json",
        "batch-submit.schema.json",
        "folder-create.schema.json",
        "worker-request.schema.json",
    ]:
        document = read_source(name)
        outputs[name] = {key: embedded(value) for key, value in document.items()}
        outputs[name]["$comment"] = (
            "Embedded shapes generated by scripts/sync-contracts.py; edit the canonical business schemas, then regenerate."
        )
    outputs["project.schema.json"]["properties"].update(
        {
            "soundtrack": soundtrack,
            "composition": composition,
            "text_layers": layers,
        }
    )
    outputs["project.schema.json"]["$id"] = "urn:reupmatic:project:1"
    outputs["project.schema.json"]["title"] = "Reupmatic project"
    worker = outputs["worker-request.schema.json"]
    branches = worker["allOf"][1]["oneOf"]
    by_method = {
        branch["properties"]["method"]["const"]: branch["properties"]["params"]
        for branch in branches
    }
    asset_id = {"type": "string", "minLength": 1, "maxLength": 128}
    canvas = object_schema(
        {key: {"type": "integer", "minimum": 2, "maximum": 16384} for key in ["width", "height"]},
        ["width", "height"],
    )
    by_method["asset.register"]["properties"]["kind"]["enum"] = ["video", "subtitle", "audio"]
    for method in ["subtitles.preview", "subtitles.save"]:
        by_method[method]["properties"].update(
            {"cues": shape(cues), "style": style, "canvas": canvas}
        )
    by_method["subtitles.save"]["properties"]["format"] = {"enum": ["srt", "ass"]}
    additions = {
        "synthesis.status": object_schema({}, []),
        "synthesis.configure": object_schema(
            {"path": {"type": "string", "minLength": 1, "maxLength": 4096}}, ["path"]
        ),
        "synthesis.configure-clone": object_schema(
            {"path": {"type": "string", "minLength": 1, "maxLength": 4096}}, ["path"]
        ),
        "synthesis.unconfigure-clone": object_schema(
            {"directory": {"type": "string", "minLength": 1, "maxLength": 4096}}, ["directory"]
        ),
        "synthesis.clone": object_schema({"asset_id": asset_id}, ["asset_id"]),
        "synthesis.cloud-voices": object_schema(
            {
                "provider": object_schema(
                    {
                        "protocol": {"type": "string", "minLength": 1, "maxLength": 64},
                        "endpoint_host": {"type": "string", "minLength": 1, "maxLength": 255},
                    },
                    ["protocol", "endpoint_host"],
                ),
                "credential": {"type": "string", "minLength": 1, "maxLength": 4096},
            },
            ["provider", "credential"],
        ),
        "speech.synthesize": copy.deepcopy(synthesis["worker_params"]),
        "translation.status": object_schema({}, []),
        "translation.configure": object_schema(
            {"path": {"type": "string", "minLength": 1, "maxLength": 4096}}, ["path"]
        ),
        "speech.translate": copy.deepcopy(translation["worker_params"]),
        "speech.status": object_schema({}, []),
        "speech.configure": object_schema(
            {"path": {"type": "string", "minLength": 1, "maxLength": 4096}}, ["path"]
        ),
        "speech.transcribe": copy.deepcopy(speech["worker_params"]),
        "audio.probe": object_schema({"asset_id": asset_id}, ["asset_id"]),
        "media.probe-file": object_schema(
            {"path": {"type": "string", "minLength": 1, "maxLength": 4096}}, ["path"]
        ),
        "subtitles.prepare": object_schema(
            {
                "asset_id": asset_id,
                "cues": shape(cues),
                "editing": editing,
                "style": style,
                "canvas": canvas,
            },
            ["asset_id", "cues"],
        ),
    }
    for method, params in additions.items():
        previous = next(
            (branch for branch in branches if branch["properties"]["method"]["const"] == method),
            None,
        )
        branch = {"properties": {"method": {"const": method}, "params": params}}
        if previous:
            branches[branches.index(previous)] = branch
        else:
            branches.append(branch)
    audio = copy.deepcopy(soundtrack)
    del audio["properties"]["source"]
    audio["properties"].update(
        {"asset_id": asset_id, "sha256": {"type": "string", "pattern": "^[a-f0-9]{64}$"}}
    )
    audio["required"] = list(audio["properties"])
    montage = copy.deepcopy(composition)
    montage["properties"]["clips"]["items"]["properties"]["source"] = object_schema(
        {
            "asset_id": asset_id,
            "sha256": {"type": "string", "pattern": "^[a-f0-9]{64}$"},
            "duration_ms": {"type": "integer", "minimum": 1, "maximum": 86400000},
        },
        ["asset_id", "sha256", "duration_ms"],
    )
    for method in ["media.render", "media.process"]:
        for variant in by_method[method]["oneOf"]:
            variant["properties"].update({"soundtrack": audio, "composition": montage})
    return outputs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = compose()
    for name, value in outputs.items():
        text = biome_format(json.dumps(value, indent=2, ensure_ascii=False) + "\n", name)
        target = CONTRACTS / name
        if args.check:
            if target.read_text(encoding="utf-8") != text:
                raise SystemExit(f"Outdated composed contract: {name}")
        else:
            target.write_text(text, encoding="utf-8")
    operations_text = ruff_format(operations_module(outputs["worker-request.schema.json"]))
    operations_target = ROOT / "worker" / "runtime" / "operations.py"
    if args.check:
        if operations_target.read_text(encoding="utf-8") != operations_text:
            raise SystemExit("Outdated generated worker/runtime/operations.py")
    else:
        operations_target.write_text(operations_text, encoding="utf-8")
    print("Current cue, processing, project and worker contracts are synchronized.")


if __name__ == "__main__":
    main()
