import { assertCues, type Cue } from '../cues.js';
import {
  createTextLayers, getTextLayer, parseTextLayers, plainCues, sameText, textLayerNames,
  type LayerOrigin, type TextLanguage, type TextLayerName, type TextSnapshot,
} from './document.js';

interface EditOptions { language?: TextLanguage; origin?: LayerOrigin }
export interface LayerCopyPreview {
  from: TextLayerName;
  to: TextLayerName;
  source_token: string;
  target_token: string;
  language: TextLanguage;
  cues: Cue[];
}

/** Invalidation changes metadata only; downstream text is never regenerated by editing. */
export function editTextLayer<T extends TextSnapshot>(
  snapshot: T, name: TextLayerName, value: Cue[], options: EditOptions = {},
): T {
  assertCues(value);
  const before = getTextLayer(snapshot, name);
  const cues = name === 'displayed' ? structuredClone(value) : plainCues(value);
  const language = options.language === undefined ? before.language : options.language;
  const textChanged = !sameText(before.cues, cues) || language !== before.language;
  if (!textChanged && !options.origin) {
    return name === 'displayed' ? { ...structuredClone(snapshot), cues } : structuredClone(snapshot);
  }
  const layers = structuredClone(snapshot.text_layers ?? createTextLayers());
  const next = {
    token: crypto.randomUUID(), language, origin: options.origin ?? before.origin,
    edited: !options.origin, stale: options.origin ? false : before.stale,
  };
  if (name === 'displayed') layers.displayed = next;
  else layers[name] = { ...next, cues };
  const changed = new Set<TextLayerName>([name]);
  for (let pass = 0; pass < textLayerNames.length; pass++) {
    for (const other of textLayerNames) {
      if (other === name || changed.has(other)) continue;
      const origin = layers[other].origin;
      if ((origin.kind === 'copy' || origin.kind === 'translation') && changed.has(origin.layer)) {
        layers[other].stale = true;
        changed.add(other);
      }
    }
  }
  return { ...structuredClone(snapshot), ...(name === 'displayed' ? { cues } : {}),
    text_layers: parseTextLayers(layers) };
}

export function previewLayerCopy(
  snapshot: TextSnapshot, from: TextLayerName, to: TextLayerName,
): LayerCopyPreview {
  if (from === to) throw new Error('INVALID_TEXT_LAYERS');
  const source = getTextLayer(snapshot, from), target = getTextLayer(snapshot, to);
  if (source.stale) throw new Error('TEXT_LAYER_STALE');
  if (!source.cues.length) throw new Error('TEXT_LAYER_EMPTY');
  const styles = new Map(target.cues.map(cue => [cue.id, cue.style]));
  const cues = plainCues(source.cues).map(cue => to === 'displayed' && styles.get(cue.id)
    ? { ...cue, style: structuredClone(styles.get(cue.id)) } : cue);
  return { from, to, source_token: source.token, target_token: target.token, language: source.language, cues };
}

function validateCopyPreview(snapshot: TextSnapshot, preview: LayerCopyPreview): void {
  let current: LayerCopyPreview;
  try { current = previewLayerCopy(snapshot, preview.from, preview.to); }
  catch { throw new Error('STALE_OPERATION'); }
  if (JSON.stringify(preview) !== JSON.stringify(current)) throw new Error('STALE_OPERATION');
}

export function applyLayerCopy<T extends TextSnapshot>(snapshot: T, preview: LayerCopyPreview): T {
  validateCopyPreview(snapshot, preview);
  return editTextLayer(snapshot, preview.to, preview.cues, {
    language: preview.language, origin: { kind: 'copy', layer: preview.from, token: preview.source_token },
  });
}

/** A human reviewed the changed source but explicitly keeps the target's words/times. */
export function reviewLayerSource<T extends TextSnapshot>(snapshot: T, preview: LayerCopyPreview): T {
  const target = getTextLayer(snapshot, preview.to);
  if (!target.stale || (target.origin.kind !== 'copy' && target.origin.kind !== 'translation') || target.origin.layer !== preview.from) {
    throw new Error('STALE_OPERATION');
  }
  validateCopyPreview(snapshot, preview);
  if (target.origin.kind === 'translation' && preview.language !== null
    && preview.language !== target.origin.source_language) throw new Error('TRANSLATION_LANGUAGE_MISMATCH');
  const next = editTextLayer(snapshot, preview.to, target.cues, { origin: {
    ...target.origin, token: preview.source_token,
  } });
  next.text_layers![preview.to].edited = true;
  return next;
}
