import type { VoiceTrack, VoiceTrackSnapshot } from '../../speech/synthesis/voice-track.js';
import { withoutVoiceTrack } from '../../speech/synthesis/voice-track.js';
import type { TranslationLanguage } from '../../speech/translation/rules.js';
import { assertCues, type Cue } from '../cues.js';
import {
  createTextLayers,
  getTextLayer,
  type LayerOrigin,
  layerCues,
  parseTextLayers,
  sameText,
  type TextLanguage,
  type TextLayerName,
  type TextSnapshot,
  textLayerNames,
} from './document.js';

interface EditOptions {
  language?: TextLanguage;
  origin?: LayerOrigin;
}
export interface LayerCopyPreview {
  from: TextLayerName;
  to: TextLayerName;
  source_token: string;
  target_token: string;
  language: TextLanguage;
  cues: Cue[];
}

/** Invalidation changes metadata only; downstream text is never regenerated by editing. */
export function editTextLayer<T extends TextSnapshot>(
  snapshot: T,
  name: TextLayerName,
  value: Cue[],
  options: EditOptions = {},
): T {
  assertCues(value);
  const before = getTextLayer(snapshot, name);
  const cues = name === 'displayed' ? structuredClone(value) : layerCues(value);
  const language = options.language === undefined ? before.language : options.language;
  const textChanged = !sameText(before.cues, cues) || language !== before.language;
  if (!textChanged && !options.origin) {
    return name === 'displayed'
      ? { ...structuredClone(snapshot), cues }
      : structuredClone(snapshot);
  }
  const layers = structuredClone(snapshot.text_layers ?? createTextLayers());
  const next = {
    token: crypto.randomUUID(),
    language,
    origin: options.origin ?? before.origin,
    edited: !options.origin,
    stale: options.origin ? false : before.stale,
    visible: before.visible,
  };
  if (name === 'displayed') layers.displayed = next;
  else layers[name] = { ...next, cues };
  const changed = new Set<TextLayerName>([name]);
  for (let pass = 0; pass < textLayerNames.length; pass++) {
    for (const other of textLayerNames) {
      if (other === name || changed.has(other)) continue;
      const origin = layers[other].origin;
      if ((origin.kind === 'copy' || origin.kind === 'translation') && changed.has(origin.layer)) {
        layers[other].stale = true;
        changed.add(other);
      }
    }
  }
  // A voice track goes stale with the layer it reads, like a derived text layer.
  const voice = (snapshot as TextSnapshot & VoiceTrackSnapshot).voice_track;
  const staleVoice = voice !== undefined && changed.has(voice.origin.layer);
  const base = {
    ...structuredClone(snapshot),
    ...(name === 'displayed' ? { cues } : {}),
    text_layers: parseTextLayers(layers),
  };
  return (
    staleVoice && !voice.stale
      ? { ...base, voice_track: { ...structuredClone(voice), stale: true } }
      : base
  ) as T;
}

/** Only one layer is visible at a time; cues are never touched. */
export function setLayerVisibility<T extends TextSnapshot>(
  snapshot: T,
  name: TextLayerName,
  visible: boolean,
): T {
  if (!textLayerNames.includes(name)) throw new Error('INVALID_TEXT_LAYERS');
  const layers = parseTextLayers(structuredClone(snapshot.text_layers ?? createTextLayers()));
  for (const layer of textLayerNames) layers[layer].visible = layer === name && visible;
  return { ...structuredClone(snapshot), text_layers: layers };
}

export function previewLayerCopy(
  snapshot: TextSnapshot,
  from: TextLayerName,
  to: TextLayerName,
): LayerCopyPreview {
  if (from === to) throw new Error('INVALID_TEXT_LAYERS');
  const source = getTextLayer(snapshot, from),
    target = getTextLayer(snapshot, to);
  if (source.stale) throw new Error('TEXT_LAYER_STALE');
  if (!source.cues.length) throw new Error('TEXT_LAYER_EMPTY');
  const styles = new Map(target.cues.map((cue) => [cue.id, cue.style]));
  // A copied cue records the source cue it came from explicitly; sync never guesses by id.
  const cues = layerCues(source.cues).map(({ split_from_cue_id: _split, ...cue }) => ({
    ...cue,
    source_cue_id: cue.id,
    ...(to === 'displayed' && styles.get(cue.id)
      ? { style: structuredClone(styles.get(cue.id)) }
      : {}),
  }));
  return {
    from,
    to,
    source_token: source.token,
    target_token: target.token,
    language: source.language,
    cues,
  };
}

function validateCopyPreview(snapshot: TextSnapshot, preview: LayerCopyPreview): void {
  let current: LayerCopyPreview;
  try {
    current = previewLayerCopy(snapshot, preview.from, preview.to);
  } catch {
    throw new Error('STALE_OPERATION');
  }
  if (JSON.stringify(preview) !== JSON.stringify(current)) throw new Error('STALE_OPERATION');
}

export function applyLayerCopy<T extends TextSnapshot>(snapshot: T, preview: LayerCopyPreview): T {
  validateCopyPreview(snapshot, preview);
  return editTextLayer(snapshot, preview.to, preview.cues, {
    language: preview.language,
    origin: { kind: 'copy', layer: preview.from, token: preview.source_token },
  });
}

/** Reviewed but keeps the target's words and times. */
export function reviewLayerSource<T extends TextSnapshot>(
  snapshot: T,
  preview: LayerCopyPreview,
): T {
  const target = getTextLayer(snapshot, preview.to);
  if (
    !target.stale ||
    (target.origin.kind !== 'copy' && target.origin.kind !== 'translation') ||
    target.origin.layer !== preview.from
  ) {
    throw new Error('STALE_OPERATION');
  }
  validateCopyPreview(snapshot, preview);
  if (
    target.origin.kind === 'translation' &&
    preview.language !== null &&
    preview.language !== target.origin.source_language
  )
    throw new Error('TRANSLATION_LANGUAGE_MISMATCH');
  const next = editTextLayer(snapshot, preview.to, target.cues, {
    origin: {
      ...target.origin,
      token: preview.source_token,
    },
  });
  if (!next.text_layers) throw new Error('INVALID_STATE');
  next.text_layers[preview.to].edited = true;
  return next;
}

export interface StaleLayerSource {
  from: TextLayerName;
  /** Set while the source's language differs from the one a translation was made from. */
  language?: { current: TranslationLanguage; expected: TranslationLanguage };
}

/** The layer a stale copy or translation must be reviewed against, or null when none applies. */
export function staleLayerSource(
  snapshot: TextSnapshot,
  name: TextLayerName,
): StaleLayerSource | null {
  const { stale, origin } = getTextLayer(snapshot, name);
  if (!stale || (origin.kind !== 'copy' && origin.kind !== 'translation')) return null;
  const current = getTextLayer(snapshot, origin.layer).language;
  return origin.kind === 'translation' && current !== null && current !== origin.source_language
    ? { from: origin.layer, language: { current, expected: origin.source_language } }
    : { from: origin.layer };
}

/** Accepts a stale voice track by repointing its origin at its source layer's token. */
export function acceptStaleVoiceTrack<T extends TextSnapshot & VoiceTrackSnapshot>(snapshot: T): T {
  const voice: VoiceTrack | undefined = snapshot.voice_track;
  if (!voice?.stale) throw new Error('STALE_OPERATION');
  const source = getTextLayer(snapshot, voice.origin.layer);
  if (source.stale) throw new Error('STALE_OPERATION');
  // Nothing is left to keep once the last line is gone; the track is removed instead.
  if (!voice.plan.lines.length) return withoutVoiceTrack(snapshot);
  return {
    ...structuredClone(snapshot),
    voice_track: {
      ...structuredClone(voice),
      origin: { ...voice.origin, token: source.token },
      stale: false,
    },
  };
}
